export const SEARCH_SUPERHEROS_WATCHER = "SEARCH_SUPERHEROS_WATCHER";
export const SEARCH_SUPERHEROS_SUCCESS = "SEARCH_SUPERHEROS_SUCCESS";
export const SEARCH_SUPERHEROS_FAILURE = "SEARCH_SUPERHEROS_FAILURE";

export const GET_SUPERHERO_PROFILE_WATCHER = "GET_SUPERHERO_PROFILE_WATCHER";
export const GET_SUPERHERO_PROFILE_SUCCESS = "GET_SUPERHERO_PROFILE_SUCCESS";
export const GET_SUPERHERO_PROFILE_FAILURE = "GET_SUPERHERO_PROFILE_FAILURE";

export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";
